name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
    needs: [test, lint]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Strip binary
        run: strip target/release/release-test
      - name: Create tarball
        run: |
          cd target/release
          tar czf ../release-test-${{ matrix.target }}.tar.gz release-test
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: target/*.tar.gz
      - name: Upload checksum
        uses: actions/upload-artifact@v2
        with:
          name: checksum
          path: target/*.sha256
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create checksums
        run: sha256sum -b *.tar.gz > checksums.sha256
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.sha256,*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
