name: Publish
on:
  push:
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Strip binary
        run: strip target/release/release-test
      - name: Create tarball
        run: |
          cd target/release
          tar czf ../release-test-${{ matrix.target }}.tar.gz release-test
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          path: target/*.tar.gz
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create checksums
        run: |
          cd artifact
          sha256sum -b *.tar.gz > ../checksums.sha256
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "checksums.sha256,artifact/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
