name: Publish
on:
  push:
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Strip binary
        if: runner.os != 'Windows'
        run: strip target/release/release-test
      - name: Create tarball
        if: runner.os != 'Windows'
        run: |
          cd target/release
          tar czf ../release-test-${{ matrix.target }}.tar.gz release-test
      - name: Create zip
        if: runner.os == 'Windows'
        run: |
          cd target/release
          7z a ../release-test-${{ matrix.target }}.zip release-test.exe
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.build }}
          path: |
            target/*.tar.gz
            target/*.zip
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create checksums
        run: |
          for dir in $(pwd)/artifact-*; do
            cd $dir
            sha256sum -b * >> ~/checksums.sha256
          done
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "~/checksums.sha256,artifact-*/*"
          token: ${{ secrets.GITHUB_TOKEN }}
